# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49bd6eb1681733fe52174a39e24c0911008f81e85acb924bd0236acc3d1bb1caec460727797559bd126efcf3b2b40fc5e5303217ee10eda437bef579a2ebac5b

test:
  secret_key_base: 5323335e5b4ef1a83e577e2d155457b34c9fc5612621fedee4fa55fd3d6e173a3a8901eb3720f08347e4bdf91833cbc881bbce983a1542fd1f88868832de43a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
